export const ERROR = {
  internal: 'Server has got an error. Please try later.',
  address: 'We couldn`t find your address on the map. Please enter valid one.',
  imageExt: 'Wrong file format. You can download only jpg, jpeg, png.',
  maxSize: 'Maximum file size (2M) was exceeded.',
  unauthorized: 'Your session has expired. Please login to continue',
  emptyFile: 'The file you are trying to upload is empty',
  apartments: {
    emptyManual: 'Please enter the number of apartment to add',
    numberExists: 'This apartment already exists in this building',
    chooseStyle: 'Please select numbering style',
    setStart: '"Start" should be a valid number',
    setFinish: '"Finish" should be a valid number',
    limitReached: 'You have reached limit for your tariff plan',
    startGreater: '"Start" should not be greater then or equal "Finish"',
    levelExists: 'This level already exists in this building',
    createLevel: 'You got no level selected. To add apartments please create one.'
  },
  moveIn: 'You can\'t book a Moving In as you haven\'t moved out of apartment yet',
  movedInAlready: 'You have already moved in this apartment',
  moveOut: 'You can\'t book a Moving Out as you haven\'t moved into apartment yet',
  movedOutAlready: 'You have already moved out this apartment',
  movingOut: 'You can\'t do this while moving out',
  fileExt: 'Wrong file format. You can upload only jpeg, jpg, png or PDF.',
  maxGuidelinesDirSize: 'Your upload limit for guidelines directory (15MB) exceeded. Delete something to continue upload',
  pdfExt: 'Wrong file format. You can upload only PDF.',
  maxSizeGuidelinesFile: 'The import file is too large to upload. The maximum size of a file that can be uploaded in guidelines directory is 15 MB.',
  maxSizeNoticefiles: 'The import file is too large to upload. The maximum size of a file that can be uploaded in notice files directory is 15 MB.',
  maxSizeCommonAreasFile: 'The import file is too large to upload. The maximum size of a file that can be uploaded in common areas directory is 15 MB.',
  maxSizeInfo: 'You can upload at once 25MB. Please save changes to upload more files.',
  maxSizePdfNotif: 'The import file is too large to upload. The maximum size of a file that can be uploaded is 15 MB.',
  maxSizeAccess: 'The import file is too large to upload. The maximum size of a file that can be uploaded is 10 MB.',
  subscription: 'Your subscription is not active, the building can not go live.',
  noSubscription: 'Billing details are not available, please fill payment information.',

}